### PR TITLE
Review AirBnB CSS Styles + RCSS and add our modifications if needed

### PR DESCRIPTION
**Pull request by katlavan**

### CODE REVIEW

**Comment by katlavan** [comment]
@pftg Please take a look.In doc added important rules for our implementation for else added links. Please verify.

**Comment by katlavan** [comment]
@pftg Also will be great to add some rules about file structure. BEM structure is good but IMO something more simpler like [this](http://www.sitepoint.com/architecture-sass-project/) wil be good for us. What do you think?

**Comment by pftg** [comment]
@katlavan :+1: for file structure

**Comment by katlavan** [comment]
@pftg Added. Please verify.

**Pull request merged**
