### PR TITLE
Update good commit message reference link.

### PR DESCRIPTION
**Pull request by askel4dd**

### CODE REVIEW

**Comment by askel4dd** [comment]
@pftg Please, take a look.

**Comment by pftg** [comment]
1. [ ] Do not remove old link, better to left ref to it as another way too
2. [ ] Pls describe in the PR why did you change to new link?

**Comment by pftg** [comment]
@askel4dd review my comment

**Comment by askel4dd** [comment]
@pftg 
Current commit message reference post is great because its short and give minimum required information in 5 minutes reading, but i think post is not memorable. I propose new reference link with more explanatory and list of rules, that you can remember.

I can leave old link as main and add new to `other` list.

**Pull request merged**
